### ISSUE TITLE
Readme example mixes ES2015 and non-ES2015 code

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/term-img#2]
`require` instead of `import`

VS.

`{fallback}` instead of `{fallback:fallback}`

Definitely a minor nit.

**Comment by sindresorhus** [comment]
I only use ES2015 features supported in the latest LTS of Node.js. The examples should be copy-pastable. `import` isn't even close to being available in Node.js natively. Does that make sense?

**Comment by jamestalmage** [comment]
:+1:
